// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SelectFile():Promise<main.FileInfo|Error>;

export function CompressFile(arg1:main.CompressionOptions):Promise<Error>;
